---
include:
  - board: cosmos_lemon_wireless
    shield: cosmotyl_left
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_RGB_UNDERGLOW=y
  - board: cosmos_lemon_wireless
    shield: cosmotyl_right
    snippet: zmk-usb-logging
    cmake-args: -DCONFIG_ZMK_RGB_UNDERGLOW=y
  - board: cosmos_lemon_wireless
    shield: settings_reset
